# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Virtual DOM Gallery
tagline:          'Showcase for reusable components using virtual DOM'
description:      'Showcasing the powerful new way to write reusable components enabled by <a href="https://github.com/Matt-Esch/virtual-dom">virtual DOM</a>.'
url:              http://virtualdom.gallery
baseurl:          /

author:
  name:           'Nick Matantsev'
  url:            https://twitter.com/unframework

paginate:         5
