# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Virtual DOM Gallery
tagline:          'Showcase for reusable components using virtual DOM'
description:      'Showcasing the powerful new way to write reusable components enabled by <a href="//virtualdom.gallery/what-is-virtual-dom/">virtual DOM</a>.'
url:              http://virtualdom.gallery
baseurl:          /

host:             0.0.0.0

author:
  name:           'Nick Matantsev'
  url:            https://twitter.com/unframework

paginate:         5
